# Generated by Django 4.2.3 on 2024-07-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cold',
            name='name',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
