# Generated by Django 4.2.3 on 2024-08-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_cold_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='headache_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('name', models.CharField(default='Null', max_length=200)),
            ],
        ),
    ]
